### ISSUE TITLE
SEQ64 has been updated, please include the latest version

### ISSUE THREAD

**Issue by sauraen** [derselbst/N64SoundTools#2]
SEQ64 has been updated with several bugfixes and additional features: https://github.com/sauraen/seq64/

Please update the copy of seq64.exe, the romdesc folder, and the source code in N64MidiTool from my repo above. If you're in contact with SubDrag, it would be nice if you could ask him to include these resources in the official release as well. If you need me to help update the RomDescs for games my repo does not include, let me know.

**Comment by derselbst** [comment]
I'm not in touch with SubDrag. I only grab the latest tarball of his tools and publish it here. This is only an unofficial mirror and I'm not willing to include latest versions of 3rd party libs, as SubDrag might have a reason not to do so. You should ask him directly to include the latest versions of your tools. Sry.

**Comment by sauraen** [comment]
I contacted SubDrag and he has updated the copy of SEQ64 included in the codebase on his end. Please pull the changes from him. Thanks.

**Comment by derselbst** [comment]
Done. He removed the source code of seq64. I did that as well, hope you dont mind.
