### ISSUE TITLE
Feature Request: zzromtool compatiblity

### ISSUE THREAD

**Issue by ariahiro64** [derselbst/N64SoundTools#3]
zzromtool is a tool that exposes the file system for oot debug. in the past i have to make an extra rom and transplant the changes because the tool doesnt work with it. you really just need to have the user point to the project .zzrp the banks are in misc and main code files are in code.
https://wiki.cloudmodding.com/oot/File_List/Debug should assist finding the offsets from the start of the file as you just do rom offset-start of file in vrom.

**Comment by derselbst** [comment]
This is just an archive repo. Pls. report you wishes to https://github.com/jombo23/N64-Tools

**Comment by ariahiro64** [comment]
thanks for pointing me in the right place.
